### ISSUE TITLE
FileNotFoundError: [Errno2]

### ISSUE THREAD

**Issue by jtbarker** [Mortiniera/collaborative-image-inpainting#1]
Running: python main.py --is_train=true --iters=25000 --dataset=fashion_mnist

Result:
FileNotFoundError: [Errno 2] No such file or directory: '/content/collaborative-image-inpainting/fixed_z.pkl'

**Comment by Mortiniera** [comment]
Thank you for the feedback. It should have been fixed by now, please check the new version.
The "fixed_z.pkl" was a presaved latent vector z (random noise) used to be able to observe the evolution of the generated images from a consistent fixed random vector. I added it back and it should be working now.

**Comment by Mortiniera** [comment]
Thank you for the feedback. It should have been fixed by now. The "fixed_z.pkl" was a pre-saved latent vector z (random noise) used to be able to observe the evolution of the generated images from a consistent fixed random vector. I added it back and it should be working now. , please check the new version and keep me updated if anything goes wrong :)

**Comment by Mortiniera** [comment]
Please note that I updated the repository readme with a link to my trained model and saved latent vectors for reproducibility.
